development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://kuucpzvbdimfkf:uGqtfQoxzBJKszho3SEAnKQy-D@ec2-23-23-225-246.compute-1.amazonaws.com:5432/d38seh9vuhjsit
